inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Description: ドキュメントの無い public class を許可する
  Enabled: false

RSpec/ExampleLength:
  Max: 20

Rails:
  Enabled: true

AllCops:
  Exclude:
    - "vendor/**/*"
    - "log/**/*"
    - "bin/**/*"
    - "db/seeds.rb"
    - "db/*schema.rb"
    - "db/**/*"
    - "tmp/**/*"
    - "public/**/*"
    - "coverage/**/*"
    - "middleware/**/*"
    - "node_modules/**/*"
    - "lib/json_web_token.rb"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
  DisplayCopNames: true

Style/AsciiComments:
  Description: 日本語のコメントを検出しない
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Exclude:
    - "app/models/post.rb"
    - "app/models/user.rb"

RSpec/MultipleExpectations:
  Max: 3
